### ISSUE TITLE
Invalid linker flag in pkgconfig file

### ISSUE THREAD

**Issue by fatih-asici** [dbus-asio/dbus-asio#1]
ld returns error when using the flags specified in pkgconfig file:

```sh
$ g++ -o pummel-server pummel-server.cpp `pkg-config --cflags --libs dbus-asio`
/usr/bin/ld: cannot find -llibboost_system.so
collect2: error: ld returned 1 exit status
```

Replacing `-llibboost_system.so` with `-lboost_system` in generated .pc file fixes the issue.

Distro info:

```sh
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```

**Comment by mikecrowe** [comment]
This appears to be due to the following part of the CMakeLists.txt file:

foreach(LIB ${PRIVATE_LIBS})                                                                                                                
        get_filename_component(BARE_LIB ${LIB} NAME)                                                                                        
        set(PLATFORM_LIBS "${PLATFORM_LIBS} -l${BARE_LIB}")                                                                                 
endforeach()    

which was introduced in https://github.com/dbus-asio/dbus-asio/commit/4233e3db8a6205a6a7509d92abbb2f9d23b4be53.

It's completely bogus because it ends up adding -l-lpthread and other dodgy things to the Libs: line in the generated .pc file.
